### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by rsaurav12** [languagemaniac/grocy-server-termux#1]
I tried your setup 

Also tried to change 8080 to 8081
And restarting php-fpm and nginx

It still show http://127.0.0.1:8081 and http://localhost:8081 says "This site can't be reached"

**Comment by languagemaniac** [comment]
Hi there, I tried this at the time I posted it and worked fine. But that was a while ago

I just made a script following the instructions from other guy so I don't know much. At the time it just worked.

Now I have a server and I don't run grocy on my phone anymore, so I can't help you. Sorry about that
